version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Maps the container's port 8001 to the host
    environment:
      - input_dir=/data/input
      - output_dir=/data/output
    volumes:
      - ./input:/data/input
      - ./output:/data/output
    command: ["python", "main.py", "--mode","api"]
